var YCD = ["{\"doctype\":\"YumChartData\",\"version\":\"1.0\",\"chart\":{\"type\":\"polyline\",\"title\":\"Polyline\",\"series\":[{\"seriesName\":\"本周\",\"data\":[{\"x\":0,\"y\":36,\"labelx\":\"周一\",\"labely\":\"36\"},{\"x\":1,\"y\":32,\"labelx\":\"周二\",\"labely\":\"32\"},{\"x\":2,\"y\":34,\"labelx\":\"周三\",\"labely\":\"34\"},{\"x\":3,\"y\":26,\"labelx\":\"周四\",\"labely\":\"26\"},{\"x\":4,\"y\":28,\"labelx\":\"周五\",\"labely\":\"28\"},{\"x\":5,\"y\":22,\"labelx\":\"周六\",\"labely\":\"22\"},{\"x\":6,\"y\":19,\"labelx\":\"周日\",\"labely\":\"19\"}]},{\"seriesName\":\"上周\",\"data\":[{\"x\":0,\"y\":30,\"labelx\":\"周一\",\"labely\":\"30\"},{\"x\":1,\"y\":27,\"labelx\":\"周二\",\"labely\":\"27\"},{\"x\":2,\"y\":25,\"labelx\":\"周三\",\"labely\":\"25\"},{\"x\":3,\"y\":22,\"labelx\":\"周四\",\"labely\":\"22\"},{\"x\":4,\"y\":17,\"labelx\":\"周五\",\"labely\":\"17\"},{\"x\":5,\"y\":16,\"labelx\":\"周六\",\"labely\":\"16\"},{\"x\":6,\"y\":22,\"labelx\":\"周日\",\"labely\":\"22\"}]},{\"seriesName\":\"上两周\",\"data\":[{\"x\":0,\"y\":22,\"labelx\":\"周一\",\"labely\":\"22\"},{\"x\":1,\"y\":26,\"labelx\":\"周二\",\"labely\":\"26\"},{\"x\":2,\"y\":29,\"labelx\":\"周三\",\"labely\":\"29\"},{\"x\":3,\"y\":31,\"labelx\":\"周四\",\"labely\":\"31\"},{\"x\":4,\"y\":35,\"labelx\":\"周五\",\"labely\":\"35\"},{\"x\":5,\"y\":39,\"labelx\":\"周六\",\"labely\":\"39\"},{\"x\":6,\"y\":36,\"labelx\":\"周日\",\"labely\":\"36\"}]},{\"seriesName\":\"上三周\",\"data\":[{\"x\":0,\"y\":24,\"labelx\":\"周一\",\"labely\":\"24\"},{\"x\":1,\"y\":23,\"labelx\":\"周二\",\"labely\":\"23\"},{\"x\":2,\"y\":22,\"labelx\":\"周三\",\"labely\":\"22\"},{\"x\":3,\"y\":26,\"labelx\":\"周四\",\"labely\":\"26\"},{\"x\":4,\"y\":27,\"labelx\":\"周五\",\"labely\":\"27\"},{\"x\":5,\"y\":26,\"labelx\":\"周六\",\"labely\":\"26\"},{\"x\":6,\"y\":23,\"labelx\":\"周日\",\"labely\":\"23\"}]},{\"seriesName\":\"上四周\",\"data\":[{\"x\":0,\"y\":32,\"labelx\":\"周一\",\"labely\":\"32\"},{\"x\":1,\"y\":33,\"labelx\":\"周二\",\"labely\":\"33\"},{\"x\":2,\"y\":36,\"labelx\":\"周三\",\"labely\":\"36\"},{\"x\":3,\"y\":37,\"labelx\":\"周四\",\"labely\":\"37\"},{\"x\":4,\"y\":32,\"labelx\":\"周五\",\"labely\":\"32\"},{\"x\":5,\"y\":31,\"labelx\":\"周六\",\"labely\":\"31\"},{\"x\":6,\"y\":39,\"labelx\":\"周日\",\"labely\":\"39\"}]}],\"xtitle\":\"\",\"ytitle\":\"收入(单位:万元)\",\"showLabel\":false}}",
    "{\"doctype\":\"YumChartData\",\"version\":\"1.0\",\"chart\":{\"type\":\"bar_horizon_sidebyside\",\"title\":\"Bar-HorizontalSide-by-side\",\"series\":[{\"seriesName\":\"本周\",\"data\":[{\"x\":136,\"y\":0,\"labely\":\"周一\",\"labelx\":\"136\"},{\"x\":116,\"y\":1,\"labely\":\"周二\",\"labelx\":\"116\"},{\"x\":120,\"y\":2,\"labely\":\"周三\",\"labelx\":\"120\"},{\"x\":103,\"y\":3,\"labely\":\"周四\",\"labelx\":\"103\"},{\"x\":98,\"y\":4,\"labely\":\"周五\",\"labelx\":\"98\"},{\"x\":112,\"y\":5,\"labely\":\"周六\",\"labelx\":\"112\"},{\"x\":116,\"y\":6,\"labely\":\"周日\",\"labelx\":\"116\"}]},{\"seriesName\":\"上周\",\"data\":[{\"x\":58,\"y\":0,\"labely\":\"周一\",\"labelx\":\"58\"},{\"x\":93,\"y\":1,\"labely\":\"周二\",\"labelx\":\"93\"},{\"x\":96,\"y\":2,\"labely\":\"周三\",\"labelx\":\"96\"},{\"x\":108,\"y\":3,\"labely\":\"周四\",\"labelx\":\"108\"},{\"x\":115,\"y\":4,\"labely\":\"周五\",\"labelx\":\"115\"},{\"x\":126,\"y\":5,\"labely\":\"周六\",\"labelx\":\"126\"},{\"x\":139,\"y\":6,\"labely\":\"周日\",\"labelx\":\"139\"}]},{\"seriesName\":\"上两周\",\"data\":[{\"x\":78,\"y\":0,\"labely\":\"周一\",\"labelx\":\"78\"},{\"x\":69,\"y\":1,\"labely\":\"周二\",\"labelx\":\"69\"},{\"x\":83,\"y\":2,\"labely\":\"周三\",\"labelx\":\"83\"},{\"x\":89,\"y\":3,\"labely\":\"周四\",\"labelx\":\"89\"},{\"x\":96,\"y\":4,\"labely\":\"周五\",\"labelx\":\"96\"},{\"x\":106,\"y\":5,\"labely\":\"周六\",\"labelx\":\"106\"},{\"x\":102,\"y\":6,\"labely\":\"周日\",\"labelx\":\"102\"}]},{\"seriesName\":\"上三周\",\"data\":[{\"x\":112,\"y\":0,\"labely\":\"周一\",\"labelx\":\"112\"},{\"x\":111,\"y\":1,\"labely\":\"周二\",\"labelx\":\"111\"},{\"x\":106,\"y\":2,\"labely\":\"周三\",\"labelx\":\"106\"},{\"x\":104,\"y\":3,\"labely\":\"周四\",\"labelx\":\"104\"},{\"x\":97,\"y\":4,\"labely\":\"周五\",\"labelx\":\"97\"},{\"x\":93,\"y\":5,\"labely\":\"周六\",\"labelx\":\"93\"},{\"x\":86,\"y\":6,\"labely\":\"周日\",\"labelx\":\"86\"}]},{\"seriesName\":\"上四周\",\"data\":[{\"x\":56,\"y\":0,\"labely\":\"周一\",\"labelx\":\"56\"},{\"x\":69,\"y\":1,\"labely\":\"周二\",\"labelx\":\"69\"},{\"x\":53,\"y\":2,\"labely\":\"周三\",\"labelx\":\"53\"},{\"x\":67,\"y\":3,\"labely\":\"周四\",\"labelx\":\"67\"},{\"x\":79,\"y\":4,\"labely\":\"周五\",\"labelx\":\"79\"},{\"x\":86,\"y\":5,\"labely\":\"周六\",\"labelx\":\"86\"},{\"x\":72,\"y\":6,\"labely\":\"周日\",\"labelx\":\"72\"}]}],\"xtitle\":\"收入(单位:万元)\",\"ytitle\":\"\",\"showLabel\":false}}",
    "{\"doctype\":\"YumChartData\",\"version\":\"1.0\",\"chart\":{\"type\":\"bar_vertical_sidebyside\",\"title\":\"Bar-VerticalSide-by-side\",\"series\":[{\"seriesName\":\"本周\",\"data\":[{\"x\":0,\"y\":46,\"labelx\":\"周一\",\"labely\":\"46\"},{\"x\":1,\"y\":68,\"labelx\":\"周二\",\"labely\":\"68\"},{\"x\":2,\"y\":93,\"labelx\":\"周三\",\"labely\":\"93\"},{\"x\":3,\"y\":133,\"labelx\":\"周四\",\"labely\":\"133\"},{\"x\":4,\"y\":168,\"labelx\":\"周五\",\"labely\":\"168\"},{\"x\":5,\"y\":178,\"labelx\":\"周六\",\"labely\":\"178\"},{\"x\":6,\"y\":196,\"labelx\":\"周日\",\"labely\":\"196\"}]},{\"seriesName\":\"上周\",\"data\":[{\"x\":0,\"y\":263,\"labelx\":\"周一\",\"labely\":\"263\"},{\"x\":1,\"y\":232,\"labelx\":\"周二\",\"labely\":\"232\"},{\"x\":2,\"y\":203,\"labelx\":\"周三\",\"labely\":\"203\"},{\"x\":3,\"y\":187,\"labelx\":\"周四\",\"labely\":\"187\"},{\"x\":4,\"y\":169,\"labelx\":\"周五\",\"labely\":\"169\"},{\"x\":5,\"y\":156,\"labelx\":\"周六\",\"labely\":\"156\"},{\"x\":6,\"y\":132,\"labelx\":\"周日\",\"labely\":\"132\"}]},{\"seriesName\":\"上两周\",\"data\":[{\"x\":0,\"y\":145,\"labelx\":\"周一\",\"labely\":\"145\"},{\"x\":1,\"y\":165,\"labelx\":\"周二\",\"labely\":\"165\"},{\"x\":2,\"y\":183,\"labelx\":\"周三\",\"labely\":\"183\"},{\"x\":3,\"y\":194,\"labelx\":\"周四\",\"labely\":\"194\"},{\"x\":4,\"y\":178,\"labelx\":\"周五\",\"labely\":\"178\"},{\"x\":5,\"y\":167,\"labelx\":\"周六\",\"labely\":\"167\"},{\"x\":6,\"y\":156,\"labelx\":\"周日\",\"labely\":\"156\"}]},{\"seriesName\":\"上三周\",\"data\":[{\"x\":0,\"y\":156,\"labelx\":\"周一\",\"labely\":\"156\"},{\"x\":1,\"y\":186,\"labelx\":\"周二\",\"labely\":\"186\"},{\"x\":2,\"y\":243,\"labelx\":\"周三\",\"labely\":\"243\"},{\"x\":3,\"y\":201,\"labelx\":\"周四\",\"labely\":\"201\"},{\"x\":4,\"y\":163,\"labelx\":\"周五\",\"labely\":\"163\"},{\"x\":5,\"y\":145,\"labelx\":\"周六\",\"labely\":\"145\"},{\"x\":6,\"y\":132,\"labelx\":\"周日\",\"labely\":\"132\"}]},{\"seriesName\":\"上四周\",\"data\":[{\"x\":0,\"y\":98,\"labelx\":\"周一\",\"labely\":\"98\"},{\"x\":1,\"y\":123,\"labelx\":\"周二\",\"labely\":\"123\"},{\"x\":2,\"y\":145,\"labelx\":\"周三\",\"labely\":\"145\"},{\"x\":3,\"y\":165,\"labelx\":\"周四\",\"labely\":\"165\"},{\"x\":4,\"y\":187,\"labelx\":\"周五\",\"labely\":\"187\"},{\"x\":5,\"y\":203,\"labelx\":\"周六\",\"labely\":\"203\"},{\"x\":6,\"y\":221,\"labelx\":\"周日\",\"labely\":\"221\"}]}],\"xtitle\":\"\",\"ytitle\":\"收入(单位:万元)\",\"showLabel\":false}}",
    "{\"doctype\":\"YumChartData\",\"version\":\"1.0\",\"chart\":{\"type\":\"bar_horizon_stack\",\"title\":\"Bar-HorizontalStacked\",\"series\":[{\"seriesName\":\"本周\",\"data\":[{\"y\":0,\"x\":476,\"labely\":\"周一\",\"labelx\":\"476\"},{\"y\":1,\"x\":589,\"labely\":\"周二\",\"labelx\":\"589\"},{\"y\":2,\"x\":689,\"labely\":\"周三\",\"labelx\":\"689\"},{\"y\":3,\"x\":793,\"labely\":\"周四\",\"labelx\":\"793\"},{\"y\":4,\"x\":862,\"labely\":\"周五\",\"labelx\":\"862\"},{\"y\":5,\"x\":1056,\"labely\":\"周六\",\"labelx\":\"1056\"},{\"y\":6,\"x\":987,\"labely\":\"周日\",\"labelx\":\"987\"}]},{\"seriesName\":\"上周\",\"data\":[{\"y\":0,\"x\":652,\"labely\":\"周一\",\"labelx\":\"652\"},{\"y\":1,\"x\":487,\"labely\":\"周二\",\"labelx\":\"487\"},{\"y\":2,\"x\":712,\"labely\":\"周三\",\"labelx\":\"712\"},{\"y\":3,\"x\":762,\"labely\":\"周四\",\"labelx\":\"762\"},{\"y\":4,\"x\":846,\"labely\":\"周五\",\"labelx\":\"846\"},{\"y\":5,\"x\":963,\"labely\":\"周六\",\"labelx\":\"963\"},{\"y\":6,\"x\":1012,\"labely\":\"周日\",\"labelx\":\"1012\"}]},{\"seriesName\":\"上两周\",\"data\":[{\"y\":0,\"x\":1024,\"labely\":\"周一\",\"labelx\":\"1024\"},{\"y\":1,\"x\":876,\"labely\":\"周二\",\"labelx\":\"876\"},{\"y\":2,\"x\":678,\"labely\":\"周三\",\"labelx\":\"678\"},{\"y\":3,\"x\":845,\"labely\":\"周四\",\"labelx\":\"845\"},{\"y\":4,\"x\":946,\"labely\":\"周五\",\"labelx\":\"946\"},{\"y\":5,\"x\":512,\"labely\":\"周六\",\"labelx\":\"512\"},{\"y\":6,\"x\":486,\"labely\":\"周日\",\"labelx\":\"486\"}]},{\"seriesName\":\"上三周\",\"data\":[{\"y\":0,\"x\":864,\"labely\":\"周一\",\"labelx\":\"864\"},{\"y\":1,\"x\":843,\"labely\":\"周二\",\"labelx\":\"843\"},{\"y\":2,\"x\":879,\"labely\":\"周三\",\"labelx\":\"879\"},{\"y\":3,\"x\":851,\"labely\":\"周四\",\"labelx\":\"851\"},{\"y\":4,\"x\":799,\"labely\":\"周五\",\"labelx\":\"799\"},{\"y\":5,\"x\":861,\"labely\":\"周六\",\"labelx\":\"861\"},{\"y\":6,\"x\":873,\"labely\":\"周日\",\"labelx\":\"873\"}]},{\"seriesName\":\"上四周\",\"data\":[{\"y\":0,\"x\":1000,\"labely\":\"周一\",\"labelx\":\"1000\"},{\"y\":1,\"x\":1234,\"labely\":\"周二\",\"labelx\":\"1234\"},{\"y\":2,\"x\":999,\"labely\":\"周三\",\"labelx\":\"999\"},{\"y\":3,\"x\":987,\"labely\":\"周四\",\"labelx\":\"987\"},{\"y\":4,\"x\":965,\"labely\":\"周五\",\"labelx\":\"965\"},{\"y\":5,\"x\":921,\"labely\":\"周六\",\"labelx\":\"921\"},{\"y\":6,\"x\":810,\"labely\":\"周日\",\"labelx\":\"810\"}]}],\"xtitle\":\"收入(单位:万元)\",\"ytitle\":\"\",\"showLabel\":false}}",
    "{\"doctype\":\"YumChartData\",\"version\":\"1.0\",\"chart\":{\"type\":\"bar_vertical_stack\",\"title\":\"Bar-VerticalStacked\",\"series\":[{\"seriesName\":\"本周\",\"data\":[{\"x\":0,\"y\":476,\"labelx\":\"周一\",\"labely\":\"476\"},{\"x\":1,\"y\":589,\"labelx\":\"周二\",\"labely\":\"589\"},{\"x\":2,\"y\":689,\"labelx\":\"周三\",\"labely\":\"689\"},{\"x\":3,\"y\":793,\"labelx\":\"周四\",\"labely\":\"793\"},{\"x\":4,\"y\":862,\"labelx\":\"周五\",\"labely\":\"862\"},{\"x\":5,\"y\":1056,\"labelx\":\"周六\",\"labely\":\"1056\"},{\"x\":6,\"y\":987,\"labelx\":\"周日\",\"labely\":\"987\"}]},{\"seriesName\":\"上周\",\"data\":[{\"x\":0,\"y\":652,\"labelx\":\"周一\",\"labely\":\"652\"},{\"x\":1,\"y\":487,\"labelx\":\"周二\",\"labely\":\"487\"},{\"x\":2,\"y\":712,\"labelx\":\"周三\",\"labely\":\"712\"},{\"x\":3,\"y\":762,\"labelx\":\"周四\",\"labely\":\"762\"},{\"x\":4,\"y\":846,\"labelx\":\"周五\",\"labely\":\"846\"},{\"x\":5,\"y\":963,\"labelx\":\"周六\",\"labely\":\"963\"},{\"x\":6,\"y\":1012,\"labelx\":\"周日\",\"labely\":\"1012\"}]},{\"seriesName\":\"上两周\",\"data\":[{\"x\":0,\"y\":1024,\"labelx\":\"周一\",\"labely\":\"1024\"},{\"x\":1,\"y\":876,\"labelx\":\"周二\",\"labely\":\"876\"},{\"x\":2,\"y\":678,\"labelx\":\"周三\",\"labely\":\"678\"},{\"x\":3,\"y\":845,\"labelx\":\"周四\",\"labely\":\"845\"},{\"x\":4,\"y\":946,\"labelx\":\"周五\",\"labely\":\"946\"},{\"x\":5,\"y\":512,\"labelx\":\"周六\",\"labely\":\"512\"},{\"x\":6,\"y\":486,\"labelx\":\"周日\",\"labely\":\"486\"}]},{\"seriesName\":\"上三周\",\"data\":[{\"x\":0,\"y\":864,\"labelx\":\"周一\",\"labely\":\"864\"},{\"x\":1,\"y\":843,\"labelx\":\"周二\",\"labely\":\"843\"},{\"x\":2,\"y\":879,\"labelx\":\"周三\",\"labely\":\"879\"},{\"x\":3,\"y\":851,\"labelx\":\"周四\",\"labely\":\"851\"},{\"x\":4,\"y\":799,\"labelx\":\"周五\",\"labely\":\"799\"},{\"x\":5,\"y\":861,\"labelx\":\"周六\",\"labely\":\"861\"},{\"x\":6,\"y\":873,\"labelx\":\"周日\",\"labely\":\"873\"}]},{\"seriesName\":\"上四周\",\"data\":[{\"x\":0,\"y\":1000,\"labelx\":\"周一\",\"labely\":\"1000\"},{\"x\":1,\"y\":1234,\"labelx\":\"周二\",\"labely\":\"1234\"},{\"x\":2,\"y\":999,\"labelx\":\"周三\",\"labely\":\"999\"},{\"x\":3,\"y\":987,\"labelx\":\"周四\",\"labely\":\"987\"},{\"x\":4,\"y\":965,\"labelx\":\"周五\",\"labely\":\"965\"},{\"x\":5,\"y\":921,\"labelx\":\"周六\",\"labely\":\"921\"},{\"x\":6,\"y\":810,\"labelx\":\"周日\",\"labely\":\"810\"}]}],\"xtitle\":\"\",\"ytitle\":\"收入(单位:万元)\",\"showLabel\":false}}",
    "{\"doctype\":\"YumChartData\",\"version\":\"1.0\",\"chart\":{\"type\":\"pie\",\"title\":\"Pie\",\"series\":[{\"seriesName\":\"本周\",\"data\":[{\"x\":1025,\"labelx\":\"周一\"},{\"x\":3210,\"labelx\":\"周二\"},{\"x\":256,\"labelx\":\"周三\"},{\"x\":705,\"labelx\":\"周四\"},{\"x\":426,\"labelx\":\"周五\"},{\"x\":5041,\"labelx\":\"周六\"},{\"x\":6025,\"labelx\":\"周日\"}]},{\"seriesName\":\"上周\",\"data\":[{\"x\":2138,\"labelx\":\"周一\"},{\"x\":1235,\"labelx\":\"周二\"},{\"x\":6588,\"labelx\":\"周三\"},{\"x\":4632,\"labelx\":\"周四\"},{\"x\":1123,\"labelx\":\"周五\"},{\"x\":678,\"labelx\":\"周六\"},{\"x\":1245,\"labelx\":\"周日\"}]},{\"seriesName\":\"上两周\",\"data\":[{\"x\":2138,\"labelx\":\"周一\"},{\"x\":1235,\"labelx\":\"周二\"},{\"x\":6588,\"labelx\":\"周三\"},{\"x\":4632,\"labelx\":\"周四\"},{\"x\":1123,\"labelx\":\"周五\"},{\"x\":678,\"labelx\":\"周六\"},{\"x\":1245,\"labelx\":\"周日\"}]},{\"seriesName\":\"上三周\",\"data\":[{\"x\":1412,\"labelx\":\"周一\"},{\"x\":4272,\"labelx\":\"周二\"},{\"x\":7854,\"labelx\":\"周三\"},{\"x\":10126,\"labelx\":\"周四\"},{\"x\":1412,\"labelx\":\"周五\"},{\"x\":7154,\"labelx\":\"周六\"},{\"x\":7104,\"labelx\":\"周日\"}]},{\"seriesName\":\"上4周\",\"data\":[{\"x\":1412,\"labelx\":\"周一\"},{\"x\":4272,\"labelx\":\"周二\"},{\"x\":7854,\"labelx\":\"周三\"},{\"x\":10126,\"labelx\":\"周四\"},{\"x\":1412,\"labelx\":\"周五\"},{\"x\":7154,\"labelx\":\"周六\"},{\"x\":7104,\"labelx\":\"周日\"}]}],\"xtitle\":\"\",\"ytitle\":\"\",\"showLabel\":true,\"pieAlignment\":\"tiled\"}}"];

$(function () {
    var _p = "#graph-container";
    var CGT = $("#current-graph-text");
    yumChart.drawGraph(_p, YCD[0]);

    $(function () {
        $(window).resize(function () {
            yumChart.resizeTitle(_p)
        });

        $("#graph-polyline").click(function () {
            CGT.text("Polyline");
            yumChart.drawGraph(_p, YCD[0])
        });

        $("#graph-bar_horizon_sidebyside").click(function () {
            CGT.text("Bar Horizontal Side By Side");
            yumChart.drawGraph(_p, YCD[1])
        });

        $("#graph-bar_vertical_sidebyside").click(function () {
            CGT.text("Bar Vertical Side By Side");
            yumChart.drawGraph(_p, YCD[2])
        });

        $("#graph-bar_horizon_stack").click(function () {
            CGT.text("Bar Horizontal Stack");
            yumChart.drawGraph(_p, YCD[3])
        });

        $("#graph-bar_vertical_stack").click(function () {
            CGT.text("Bar Vertical Stack");
            yumChart.drawGraph(_p, YCD[4])
        });

        $("#graph-pie").click(function () {
            CGT.text("Pie");
            yumChart.drawGraph(_p, YCD[5])
        });
    })
});